sudo: false
language: java
addons:
  sonarcloud:
    organization: "jcgay-github"
jdk:
  - openjdk8
install: true
script:
  - mvn verify sonar:sonar -Prun-coverage -B
after_success:
  - mvn coveralls:report
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -DskipTests --settings etc/deploy-settings.xml"
env:
  global:
    - secure: XxK2hzBWO2Zvq1OEVvdFBydwQOPoRb7lXrsa+LvAFs+6UzwDzPKYmPwwFmKYQUQRl4QxhXWmIvrUSwRLc8n4cJeXOZlzG7fsn68fwcD07K1Znpb9uFa62rdvPeUjrLBNoNFjIojA4FEyzOXFFTHQ9YzA+BQQG1YPqQB5XD9LefU=
    - secure: do931S+S2IpcCyk5IkGrAQnGonCYvnCVhWM/MP5dxJovDuI/Va4LtZRPWmnnm1S8UwPlThvCiWxhsjBd6GRzk0fJ/PsfHhCER3EHvvwT6GWNsuX/HnEuNfn9LWNC1dgIi05xGq/QTjRB/WIs+ChLhyvO/9X3LuSpz5gCEqkU/CU=
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
