# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "jhcook/osx-yosemite-10.10"

  config.vm.network "private_network", ip: "10.0.0.100"

  # Application binaries we want to test
  config.vm.synced_folder "../../../target", "/app", type: "nfs"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.vm.provider "virtualbox" do |vb|
     # Don't boot with headless mode
     vb.gui = true
     vb.memory = 4096
     vb.cpus = 4
  end

  config.vm.provision :shell, :path => "xcode-cli-tools.sh"
  config.vm.provision :shell, :path => "brew.sh", privileged: false
  config.vm.provision :shell, :path => "install-notifiers.sh", privileged: false

end
