# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "box-cutter/ubuntu1404-desktop"

  # Application binaries we want to test
  config.vm.synced_folder "../../../target", "/app"

  config.vm.provider "virtualbox" do |vb|
     # Don't boot with headless mode
     vb.gui = true
  end

  config.vm.provision :shell, :path => "install-notifiers.sh"
  config.vm.provision :shell, :path => "install-tools.sh"

end
